### ISSUE TITLE
Sedna version

### ISSUE THREAD

**Issue by avancise** [MMARINeDNA/metabarcoding_QAQC_pipeline#1]
Make a version of the QAQC pipeline that runs automatically in Sedna. Ideally, this pipeline will automatically pull the sequences from the QNAP, move them to Sedna, process, then delete the sequences from their temporary location.

**Comment by alexandriai168** [comment]
done! 2 inputs when you start the job (no more interactive mode) and removes intermediate files as the pipeline runs
