### ISSUE TITLE
Path errors: `scripts`

### ISSUE THREAD

**Issue by invertdna** [MMARINeDNA/metabarcoding_QAQC_pipeline#13]
I believe `scripts` has been replaced by `bin`, and so paths pointing at `scripts` are broken.

**Comment by invertdna** [comment]
still having this issue:  `sh: ../../bin/primer_trimming.sh: No such file or directory`

Although I now think the setup script copies everything from `bin` in the main script folder into a `scripts` folder in the target working folder, and I'm not clear which version of the `primer_trimming.sh` the main `metabarcoding_wrapper.sh` is intending to call.

**Comment by invertdna** [comment]
for example, line 22 of `metabarcoding_wrapper.sh` has: 

`sh ../../bin/primer_trimming.sh`

But at that point in the script, the working directory should be in `{INPUT_DIR}/raw_fastqs`, and there is no `bin` folder in the `INPUT_DIR` as created by the setup script.

**Comment by alexandriai168** [comment]
fixed on config file, should be no more discrepancies between metabarcoding_wrapper.sh and config.sh
