### ISSUE TITLE
missing file `primer_test_phyloseq.Rdata`

### ISSUE THREAD

**Issue by invertdna** [MMARINeDNA/metabarcoding_QAQC_pipeline#16]
line 59 of the shell script refers to `primer_test_phyloseq.Rdata`, but that file appears to be missing.

**Comment by alexandriai168** [comment]
this error occurred because the .qmd file was pulling from a metadata file that was hardcoded. Just added new code that pulls from Hake_2019_metadata.csv and the MiSeq sample sheet to make this metadata.csv file.  The qmd should now be able to make the phyloseq Rdata.
