### ISSUE TITLE
Various Issues in `dada2QAQC.R`

### ISSUE THREAD

**Issue by invertdna** [MMARINeDNA/metabarcoding_QAQC_pipeline#23]
`fastq_location` argument passed from the wrapper script maybe should not have a trailing slash, because it creates a double slash in various paths and wrecks things.

Same thing happens with `output_location` argument, used at lines 178-181 here; creates double slashes and fails to write out

It seems like the difference between `paste0()` and `file.path()` is what’s creating these double-slash issues. You’ve got to pick one or the other and go with it.

Lines 144 and 146 can’t have the [[1]] in them, or else they throw errors?  Maybe should be just `errF <- dadaFs.lrn$err_out` and `errF <- dadaFs.lrn$err_out`

**Comment by invertdna** [comment]
Correction on lines 144/146: sometimes it needs the [[1]], and I don't know when/why

**Comment by alexandriai168** [comment]
In regards to the `errF <- dadaFs.lrn$err_out[[1]]` , this only throws an error when you only have 1 fastq file passed to the script/ only 1 makes it through the filtering step.

**Comment by alexandriai168** [comment]
fixed trailing slashes- ran through the script and made sure all paths have only 1 "/" and updated the metabarcoding wrapper to reflect that!  updated code pushed
