### ISSUE TITLE
Add Cutadapt Feature!

### ISSUE THREAD

**Issue by alexandriai168** [MMARINeDNA/metabarcoding_QAQC_pipeline#5]

**Comment by alexandriai168** [comment]
Cutadapt bug fixed! Added paired-end trimming instead of just trimming by 5' for each fastq.

**Comment by avancise** [comment]
woohooooo!!!!!


<*)))><  <*)))><  <*)))><  <*)))><  <*)))><  <*)))><  <*)))><  <*)))><
Amy M. Van Cise, Ph.D.
(she/her/hers)

Assistant Professor
University of Washington | School of Aquatic and Fisheries Sciences
1122 NE Boat St
Seattle, WA 98105
Office: SAFS 216B
